<?php

use Illuminate\Database\Seeder;

class ModulTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('modul')->delete();
        
        \DB::table('modul')->insert(array (
            0 => 
            array (
                'id_modul' => 2,
                'nama_modul' => 'Manajemen User',
                'link' => '?module=user',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 1,
                'link_seo' => '',
            ),
            1 => 
            array (
                'id_modul' => 18,
                'nama_modul' => 'Berita',
                'link' => '?module=berita',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 6,
                'link_seo' => 'semua-berita.html',
            ),
            2 => 
            array (
                'id_modul' => 19,
                'nama_modul' => 'Banner',
                'link' => '?module=banner',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 9,
                'link_seo' => '',
            ),
            3 => 
            array (
                'id_modul' => 37,
                'nama_modul' => 'Profil',
                'link' => '?module=profil',
            'static_content' => '<b>Bukulokomedia.com</b> merupakan website resmi dari penerbit Lokomedia yang bermarkas di Jl. Arwana No.24 Minomartani Yogyakarta 55581. Dirintis pertama kali oleh Lukmanul Hakim pada tanggal 14 Maret 2008.<br><br>Produk unggulan dari penerbit Lokomedia adalah buku-buku serta aksesoris bertema PHP (<span style="font-weight: bold; font-style: italic;">PHP: Hypertext Preprocessor</span>) yang merupakan pemrograman Internet paling handal saat ini.
',
                'gambar' => 'gedungku.jpg',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 3,
                'link_seo' => 'profil-kami.html',
            ),
            4 => 
            array (
                'id_modul' => 10,
                'nama_modul' => 'Manajemen Modul',
                'link' => '?module=modul',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 2,
                'link_seo' => '',
            ),
            5 => 
            array (
                'id_modul' => 31,
                'nama_modul' => 'Kategori',
                'link' => '?module=kategori',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 5,
                'link_seo' => '',
            ),
            6 => 
            array (
                'id_modul' => 33,
                'nama_modul' => 'Poling',
                'link' => '?module=poling',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 10,
                'link_seo' => '',
            ),
            7 => 
            array (
                'id_modul' => 34,
            'nama_modul' => 'Tag (Label)',
                'link' => '?module=tag',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 7,
                'link_seo' => '',
            ),
            8 => 
            array (
                'id_modul' => 35,
                'nama_modul' => 'Komentar',
                'link' => '?module=komentar',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 8,
                'link_seo' => '',
            ),
            9 => 
            array (
                'id_modul' => 36,
                'nama_modul' => 'Download',
                'link' => '?module=download',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 11,
                'link_seo' => 'semua-download.html',
            ),
            10 => 
            array (
                'id_modul' => 40,
                'nama_modul' => 'Hubungi Kami',
                'link' => '?module=hubungi',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 12,
                'link_seo' => 'hubungi-kami.html',
            ),
            11 => 
            array (
                'id_modul' => 41,
                'nama_modul' => 'Agenda',
                'link' => ' ?module=agenda',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 0,
                'link_seo' => 'semua-agenda.html',
            ),
            12 => 
            array (
                'id_modul' => 42,
                'nama_modul' => 'Shoutbox',
                'link' => '?module=shoutbox',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 13,
                'link_seo' => '',
            ),
            13 => 
            array (
                'id_modul' => 43,
                'nama_modul' => 'Album',
                'link' => '?module=album',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 14,
                'link_seo' => '',
            ),
            14 => 
            array (
                'id_modul' => 44,
                'nama_modul' => 'Galeri Foto',
                'link' => '?module=galerifoto',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 15,
                'link_seo' => '',
            ),
            15 => 
            array (
                'id_modul' => 45,
                'nama_modul' => 'Templates',
                'link' => '?module=templates',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 16,
                'link_seo' => '',
            ),
            16 => 
            array (
                'id_modul' => 46,
                'nama_modul' => 'Kata Jelek',
                'link' => '?module=katajelek',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 17,
                'link_seo' => '',
            ),
            17 => 
            array (
                'id_modul' => 47,
                'nama_modul' => 'RSS',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 18,
                'link_seo' => '',
            ),
            18 => 
            array (
                'id_modul' => 48,
                'nama_modul' => 'YM',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 19,
                'link_seo' => '',
            ),
            19 => 
            array (
                'id_modul' => 49,
                'nama_modul' => 'Indeks Berita',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 20,
                'link_seo' => '',
            ),
            20 => 
            array (
                'id_modul' => 50,
                'nama_modul' => 'Kalender',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 21,
                'link_seo' => '',
            ),
            21 => 
            array (
                'id_modul' => 51,
                'nama_modul' => 'Statistik User',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 22,
                'link_seo' => '',
            ),
            22 => 
            array (
                'id_modul' => 52,
                'nama_modul' => 'Pencarian',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 23,
                'link_seo' => '',
            ),
            23 => 
            array (
                'id_modul' => 53,
                'nama_modul' => 'Berita Teratas',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 24,
                'link_seo' => '',
            ),
            24 => 
            array (
                'id_modul' => 54,
                'nama_modul' => 'Arsip Berita',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 25,
                'link_seo' => '',
            ),
            25 => 
            array (
                'id_modul' => 55,
                'nama_modul' => 'Berita Sebelumnya',
                'link' => '-',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'N',
                'urutan' => 26,
                'link_seo' => '',
            ),
            26 => 
            array (
                'id_modul' => 60,
                'nama_modul' => 'Sekilas Info',
                'link' => '?module=sekilasinfo',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 13,
                'link_seo' => '',
            ),
            27 => 
            array (
                'id_modul' => 57,
                'nama_modul' => 'Menu Utama',
                'link' => '?module=menuutama',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 28,
                'link_seo' => '',
            ),
            28 => 
            array (
                'id_modul' => 58,
                'nama_modul' => 'Sub Menu',
                'link' => '?module=submenu',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 29,
                'link_seo' => '',
            ),
            29 => 
            array (
                'id_modul' => 59,
                'nama_modul' => 'Halaman Statis',
                'link' => '?module=halamanstatis',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 30,
                'link_seo' => '',
            ),
            30 => 
            array (
                'id_modul' => 61,
                'nama_modul' => 'Identitas Website',
                'link' => '?module=identitas',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 4,
                'link_seo' => '',
            ),
            31 => 
            array (
                'id_modul' => 62,
                'nama_modul' => 'Rencana Kegiatan',
                'link' => '?module=perkeurencana',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'N',
                'status' => 'user',
                'aktif' => 'N',
                'urutan' => 0,
                'link_seo' => '',
            ),
            32 => 
            array (
                'id_modul' => 63,
                'nama_modul' => 'Anggaran',
                'link' => '?module=anggaran',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 33,
                'link_seo' => '',
            ),
            33 => 
            array (
                'id_modul' => 64,
                'nama_modul' => 'Laporan',
                'link' => '?module=laporan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 0,
                'link_seo' => '',
            ),
            34 => 
            array (
                'id_modul' => 65,
                'nama_modul' => 'tingkat',
                'link' => '?module=tingkat',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 34,
                'link_seo' => '',
            ),
            35 => 
            array (
                'id_modul' => 66,
                'nama_modul' => 'Laporan Menurut Sasaran Strategis',
                'link' => '?module=laprenstra',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 35,
                'link_seo' => '',
            ),
            36 => 
            array (
                'id_modul' => 67,
                'nama_modul' => 'Laporan Menurut Tujuan',
                'link' => '?module=laptujuan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 36,
                'link_seo' => '',
            ),
            37 => 
            array (
                'id_modul' => 68,
                'nama_modul' => 'Laporan Menurut rencana kegiatan',
                'link' => '?module=lapkegiatan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 37,
                'link_seo' => '',
            ),
            38 => 
            array (
                'id_modul' => 69,
                'nama_modul' => 'Laporan Menurut rencana anggaran',
                'link' => '?module=lapanggaran',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'admin',
                'aktif' => 'Y',
                'urutan' => 38,
                'link_seo' => '',
            ),
            39 => 
            array (
                'id_modul' => 70,
                'nama_modul' => 'Modul Review',
                'link' => '?module=review',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'user',
                'aktif' => 'Y',
                'urutan' => 39,
                'link_seo' => '',
            ),
            40 => 
            array (
                'id_modul' => 71,
                'nama_modul' => 'Modul Review Keuangan',
                'link' => '?module=reviewkeu',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'reviewkeu',
                'aktif' => 'Y',
                'urutan' => 40,
                'link_seo' => '',
            ),
            41 => 
            array (
                'id_modul' => 72,
                'nama_modul' => 'Modul Keputusan',
                'link' => '?module=keputusan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'pimpinan',
                'aktif' => 'Y',
                'urutan' => 41,
                'link_seo' => '',
            ),
            42 => 
            array (
                'id_modul' => 73,
                'nama_modul' => 'Modul Rekap Kegiatan',
                'link' => '?module=rekapkegiatan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'all',
                'aktif' => 'Y',
                'urutan' => 42,
                'link_seo' => '',
            ),
            43 => 
            array (
                'id_modul' => 74,
                'nama_modul' => 'Modul Standart Biaya',
                'link' => '?module=standartbiaya',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'adminsbu',
                'aktif' => 'Y',
                'urutan' => 43,
                'link_seo' => '',
            ),
            44 => 
            array (
                'id_modul' => 75,
                'nama_modul' => 'Modul Akun',
                'link' => '?module=akun',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'adminsbu',
                'aktif' => 'Y',
                'urutan' => 44,
                'link_seo' => '',
            ),
            45 => 
            array (
                'id_modul' => 76,
                'nama_modul' => 'Modul Kelompok',
                'link' => '?module=kelompok',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'adminsbu',
                'aktif' => 'Y',
                'urutan' => 45,
                'link_seo' => '',
            ),
            46 => 
            array (
                'id_modul' => 77,
                'nama_modul' => 'Modul Satuan',
                'link' => '?module=satuan',
                'static_content' => '',
                'gambar' => '',
                'publish' => 'Y',
                'status' => 'adminsbu',
                'aktif' => 'Y',
                'urutan' => 46,
                'link_seo' => '',
            ),
        ));
        
        
    }
}